version: '2'

services:

  mysql:
    image: mysql:5.7.19 # same version of latest MySQL on AmazonRDS
    volumes:
      - wpdb:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - config/variables.env

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"
    env_file:
      - config/variables.env

  wp:
    build: ./config/docker
    depends_on:
      - mysql
    volumes:
      - "./:/var/www/html"
      - "./config/php-fpm/php.ini:/usr/local/etc/php/php.ini"
      - "./config/php-fpm/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
    env_file:
      - config/variables.env

  nginx:
    depends_on:
      - wp
    ports:
      - "80:80"
      - "443:443"
    image: nginx:1.12-alpine
    volumes_from:
      - wp
    volumes:
      - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./config/certs:/etc/nginx/certs"
      - "./logs/nginx:/var/log/nginx"

volumes:
  wpdb:
    driver: local
